# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cc513b9dd19d0527bd607c479e0e98e272646a1002eb17947f85f58c67e2e71cde0a1d8588c1b46a7151c033dcb2d2d021f03e459b6d1362ad59da80106ce12

test:
  secret_key_base: 428c174aa6b8654a34bfa942f3c220824335d7b1654f5a45ab73668a75de91a7a2eb47beb066176bb72f408fe2e856e05a0f2136b74b069f286b99a1396836fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
